/* eslint-disable import/prefer-default-export */
export const es = {
  BANNER_SMS: {
    DEEPLINKS: {
      ANDROID: 'https://yapo.app.link/smsinfobip',
      IOS: 'https://yapo.app.link/smsinfobip',
    },
    OPTIONS: {
      IOS: {
        NAME: 'IOS',
      },
      ANDROID: {
        NAME: 'Android',
      },
    },
    OPTION_SELECTED: 'android',
    DESCRIPTION: 'Ingresa tu <b class="bannerSMSTextBold">número de teléfono</b> y te enviaremos un enlace para descargar la app',
    SUCCESS_MSG: 'Ahora recibirás el enlace para descargar nuestra app',
    TITLE: 'Compra y vende aún más rápido con la app de',
    URL: '/sms/send_sms',
  },
  ADD_TO_FAVORITES: 'Agregar a favoritos:',
  ADDED_TO_FAVORITES: 'Agregado a favoritos:',
  DOWNLOAD_APP_MOVIL_YAPO_HERE: 'Descarga la App de Yapo aquí',
  SEND: 'Enviar',
  SENDING: 'Enviando...',
  YAPO_URL: 'Yapo.cl',
  ERRORS: {
    CONNECTION: 'Error de conexión. Intente nuevamente.',
    INVALID_NUMBER: 'Número inválido',
  },
  BUILDERS: {
    PUBLISHED_AT: 'Publicado',
    SINCE: 'Desde',
    TO:'Hasta',
    PROJECT: 'Proyecto',
    INFORMATION: 'Información',
    RENT: 'Arriendo',
    ID: 'Código',
    CODE: 'Código',
    PROPERTY_TYPE: 'Tipo de inmueble',
    COMMUNE: 'Comuna',
    BEDROOMS: 'Dormitorios',
    APARTMENT: 'Departamento',
    BATHROOMS: 'Baños',
    SERVICES: 'Servicios',
    PROPERTIES_TYPES: 'Tipos de propiedades',
    BEDROOM: 'Dormitorios',
    BATHROOM: 'Baño',
    MTS2: 'mts2',
    QUOTE: 'Cotizar',
    CARRY_US: '¡Llévanos siempre contigo! Descárgate nuestra app',
    SLOGAN: 'Yapo, compra y vende lo que quieras',
    FOLLOW_US: 'Siguenos en:',
    ANY_QUESTIONS: '¿Tienes alguna duda?',
    CONTACT_US: 'Contáctanos',
    CONTACT: 'Contactar',
    OUR_RULES: 'Lee nuestras reglas',
    COPYRIGHT: '2017 Yapo.cl SpA',
    PUBLISH: 'Publicar',
    PUBLISH_FULL: 'Publicar Aviso',
    ACCOUNT: 'Cuenta',
    HELLO: 'Hola',
    CLOSE_SESSION: 'Cerrar Sesión',
    HOME: 'Home',
    FIND_ADS: 'Buscar Avisos',
    FAVORITES: 'Favoritos',
    HELP: 'Ayuda',
    MY_ADS: 'Mis Avisos',
    STORES: 'Tiendas',
    SHARE_PROPERTY: 'Compartir Inmueble',
    QUOTE_PROJECT: 'Cotiza este proyecto',
    SAVE_PROJECT: 'Guardar proyecto',
    DESCRIPTION: 'Descripción',
    LOCATION: 'Ubicación',
    WIFI: 'WiFi',
    TV_CABLE: 'Tv Cable',
    SATELITE: 'Satélite',
    HEATING: 'Calefacción',
    EQUIPPED_KITCHEN: 'Cocina equipada',
    SHOW_MAP: 'Ver mapa',
    YES: 'Sí',
    NO: 'No',
    SOLDOUT: 'Agotado',
    PROPERTY_CHOICE_TYPE: 'Elige un tipo de propiedad',
    form: {
      NAME: 'Nombre',
      DNI: 'RUT',
      MAIL: 'Mail',
      PHONE: 'Teléfono',
      MESSAGE: 'Mensaje',
      APPROVED_CREDIT: 'Tienes crédito aprobado',
    },
  },
};
